
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace DataTables.demo
{
public partial class Tbtteess1
{
    private readonly System.Collections.Generic.Dictionary<int, demo.tteess1> _dataMap;
    private readonly System.Collections.Generic.List<demo.tteess1> _dataList;
    
    public Tbtteess1(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.tteess1>(count);
        _dataList = new System.Collections.Generic.List<demo.tteess1>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.tteess1 _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.demo.tteess1.Deserializetteess1(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, demo.tteess1> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<demo.tteess1> DataList => _dataList;

    public demo.tteess1 GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.tteess1 Get(int key) => _dataMap[key];
    public demo.tteess1 this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

