
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace DataTables.Test
{
public partial class TestDemoMap
{
    private readonly System.Collections.Generic.List<Test.TestDemo> _dataList;

    private System.Collections.Generic.Dictionary<(int, string), Test.TestDemo> _dataMapUnion;

    public TestDemoMap(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<Test.TestDemo>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Test.TestDemo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.Test.TestDemo.DeserializeTestDemo(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, string), Test.TestDemo>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.Id, _v.Name), _v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<Test.TestDemo> DataList => _dataList;

    public Test.TestDemo Get(int id, string name) => _dataMapUnion.TryGetValue((id, name), out Test.TestDemo __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

