
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace DataTables.Test
{
public sealed partial class TestDemo : Luban.BeanBase
{
    public TestDemo(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { var __json0 = _buf["prop_count"]; if(!__json0.IsArray) { throw new SerializationException(); } PropCount = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  PropCount.Add(__v0); }   }
    }

    public static TestDemo DeserializeTestDemo(JSONNode _buf)
    {
        return new Test.TestDemo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 个数
    /// </summary>
    public readonly System.Collections.Generic.List<int> PropCount;
   
    public const int __ID__ = 1138516849;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "propCount:" + Luban.StringUtil.CollectionToString(PropCount) + ","
        + "}";
    }
}
}

