
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace DataTables.Test
{
public partial class TestDemoMap
{
    private readonly System.Collections.Generic.Dictionary<int, Test.TestDemo> _dataMap;
    private readonly System.Collections.Generic.List<Test.TestDemo> _dataList;
    
    public TestDemoMap(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Test.TestDemo>(count);
        _dataList = new System.Collections.Generic.List<Test.TestDemo>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Test.TestDemo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.Test.TestDemo.DeserializeTestDemo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Test.TestDemo> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Test.TestDemo> DataList => _dataList;

    public Test.TestDemo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Test.TestDemo Get(int key) => _dataMap[key];
    public Test.TestDemo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

