
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TestDemo : Luban.BeanBase
{
    public TestDemo(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
        { if(!_buf["direction"].IsObject) { throw new SerializationException(); }  Direction = global::cfg.vector3.Deserializevector3(_buf["direction"]);  }
        { if(!_buf["ttest"].IsObject) { throw new SerializationException(); }  Ttest = global::cfg.CostDetail.DeserializeCostDetail(_buf["ttest"]);  }
    }

    public static TestDemo DeserializeTestDemo(JSONNode _buf)
    {
        return new TestDemo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 个数
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 方向
    /// </summary>
    public readonly vector3 Direction;
    /// <summary>
    /// 测试
    /// </summary>
    public readonly CostDetail Ttest;
   
    public const int __ID__ = -1082621515;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Ttest?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "count:" + Count + ","
        + "direction:" + Direction + ","
        + "ttest:" + Ttest + ","
        + "}";
    }
}
}

