
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TestDemoMap
{
    private readonly System.Collections.Generic.Dictionary<int, TestDemo> _dataMap;
    private readonly System.Collections.Generic.List<TestDemo> _dataList;
    
    public TestDemoMap(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, TestDemo>(count);
        _dataList = new System.Collections.Generic.List<TestDemo>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TestDemo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.TestDemo.DeserializeTestDemo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TestDemo> DataMap => _dataMap;
    public System.Collections.Generic.List<TestDemo> DataList => _dataList;

    public TestDemo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TestDemo Get(int key) => _dataMap[key];
    public TestDemo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

