
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace DataTables
{
public sealed partial class AchievementStageRewards : Luban.BeanBase
{
    public AchievementStageRewards(JSONNode _buf) 
    {
        { var __json0 = _buf["achievement_rewards"]; if(!__json0.IsArray) { throw new SerializationException(); } AchievementRewards = new System.Collections.Generic.List<PropData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { PropData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::DataTables.PropData.DeserializePropData(__e0);  }  AchievementRewards.Add(__v0); }   }
    }

    public static AchievementStageRewards DeserializeAchievementStageRewards(JSONNode _buf)
    {
        return new AchievementStageRewards(_buf);
    }

    public readonly System.Collections.Generic.List<PropData> AchievementRewards;
   
    public const int __ID__ = -68739339;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in AchievementRewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "achievementRewards:" + Luban.StringUtil.CollectionToString(AchievementRewards) + ","
        + "}";
    }
}
}

