
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace DataTables
{
public partial class AchievementTable
{
    private readonly System.Collections.Generic.Dictionary<int, AchievementData> _dataMap;
    private readonly System.Collections.Generic.List<AchievementData> _dataList;
    
    public AchievementTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, AchievementData>(count);
        _dataList = new System.Collections.Generic.List<AchievementData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            AchievementData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.AchievementData.DeserializeAchievementData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, AchievementData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<AchievementData> DataList => _dataList;

    public AchievementData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public AchievementData Get(int key) => _dataMap[key];
    public AchievementData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

