
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    public enum AchievementStrategyType
    {
        BossKillCount = 1,
        BossKillLowHp = 2,
        BossKillFlawless = 3,
        BossKillTimeLimit = 4,
        QuantityReach = 5,
    }

} 

