
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace DataTables
{
public sealed partial class AchievementData : Luban.BeanBase
{
    public AchievementData(JSONNode _buf) 
    {
        { if(!_buf["achievement_id"].IsNumber) { throw new SerializationException(); }  AchievementId = _buf["achievement_id"]; }
        { if(!_buf["achievement_category"].IsString) { throw new SerializationException(); }  AchievementCategory = _buf["achievement_category"]; }
        { if(!_buf["achievement_Parents"].IsString) { throw new SerializationException(); }  AchievementParents = _buf["achievement_Parents"]; }
        { if(!_buf["achievement_name"].IsString) { throw new SerializationException(); }  AchievementName = _buf["achievement_name"]; }
        { if(!_buf["achievement_desc"].IsString) { throw new SerializationException(); }  AchievementDesc = _buf["achievement_desc"]; }
        { var __json0 = _buf["achievement_targets"]; if(!__json0.IsArray) { throw new SerializationException(); } AchievementTargets = new System.Collections.Generic.List<long>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { long __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  AchievementTargets.Add(__v0); }   }
        { var __json0 = _buf["achievement_rewards"]; if(!__json0.IsArray) { throw new SerializationException(); } AchievementRewards = new System.Collections.Generic.List<AchievementStageRewards>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { AchievementStageRewards __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::DataTables.AchievementStageRewards.DeserializeAchievementStageRewards(__e0);  }  AchievementRewards.Add(__v0); }   }
    }

    public static AchievementData DeserializeAchievementData(JSONNode _buf)
    {
        return new AchievementData(_buf);
    }

    /// <summary>
    /// 成就Id
    /// </summary>
    public readonly int AchievementId;
    /// <summary>
    /// 成就大类
    /// </summary>
    public readonly string AchievementCategory;
    /// <summary>
    /// 成就父类
    /// </summary>
    public readonly string AchievementParents;
    /// <summary>
    /// 成就名称
    /// </summary>
    public readonly string AchievementName;
    /// <summary>
    /// 成就描述
    /// </summary>
    public readonly string AchievementDesc;
    /// <summary>
    /// 成就目标
    /// </summary>
    public readonly System.Collections.Generic.List<long> AchievementTargets;
    /// <summary>
    /// 成就奖励
    /// </summary>
    public readonly System.Collections.Generic.List<AchievementStageRewards> AchievementRewards;
   
    public const int __ID__ = -376145063;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in AchievementRewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "achievementId:" + AchievementId + ","
        + "achievementCategory:" + AchievementCategory + ","
        + "achievementParents:" + AchievementParents + ","
        + "achievementName:" + AchievementName + ","
        + "achievementDesc:" + AchievementDesc + ","
        + "achievementTargets:" + Luban.StringUtil.CollectionToString(AchievementTargets) + ","
        + "achievementRewards:" + Luban.StringUtil.CollectionToString(AchievementRewards) + ","
        + "}";
    }
}
}

