
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace DataTables
{
public sealed partial class CostDetail : Luban.BeanBase
{
    public CostDetail(JSONNode _buf) 
    {
        { if(!_buf["itemId"].IsNumber) { throw new SerializationException(); }  ItemId = _buf["itemId"]; }
        { if(!_buf["consume"].IsNumber) { throw new SerializationException(); }  Consume = _buf["consume"]; }
    }

    public static CostDetail DeserializeCostDetail(JSONNode _buf)
    {
        return new CostDetail(_buf);
    }

    public readonly int ItemId;
    public readonly long Consume;
   
    public const int __ID__ = 1429062302;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "consume:" + Consume + ","
        + "}";
    }
}
}

