
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace DataTables
{
public sealed partial class PropData : Luban.BeanBase
{
    public PropData(JSONNode _buf) 
    {
        { if(!_buf["enumId"].IsNumber) { throw new SerializationException(); }  EnumId = (PropEnumId)_buf["enumId"].AsInt; }
        { if(!_buf["propCounts"].IsNumber) { throw new SerializationException(); }  PropCounts = _buf["propCounts"]; }
    }

    public static PropData DeserializePropData(JSONNode _buf)
    {
        return new PropData(_buf);
    }

    public readonly PropEnumId EnumId;
    public readonly long PropCounts;
   
    public const int __ID__ = -929496627;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "enumId:" + EnumId + ","
        + "propCounts:" + PropCounts + ","
        + "}";
    }
}
}

