
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    public enum PropEnumId
    {
        金币 = 1,
        成就点 = 2,
    }

} 

