
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace DataTables
{
public partial class Tables
{
    public Test.TestDemoMap TestDemoMap {get; }
    public AchievementTable AchievementTable {get; }
    public demo.Tbtteess1 Tbtteess1 {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TestDemoMap = new Test.TestDemoMap(loader("test_testdemomap"));
        AchievementTable = new AchievementTable(loader("achievementtable"));
        Tbtteess1 = new demo.Tbtteess1(loader("demo_tbtteess1"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TestDemoMap.ResolveRef(this);
        AchievementTable.ResolveRef(this);
        Tbtteess1.ResolveRef(this);
    }
}

}
