
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace DataTables
{
public abstract partial class TestBean : Luban.BeanBase
{
    public TestBean(JSONNode _buf) 
    {
        { if(!_buf["test1"].IsNumber) { throw new SerializationException(); }  Test1 = _buf["test1"]; }
        { if(!_buf["test2"].IsNumber) { throw new SerializationException(); }  Test2 = _buf["test2"]; }
    }

    public static TestBean DeserializeTestBean(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "TestBeanChild": return new TestBeanChild(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly int Test1;
    public readonly int Test2;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "test1:" + Test1 + ","
        + "test2:" + Test2 + ","
        + "}";
    }
}
}

