
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace DataTables
{
public sealed partial class TestBeanChild : TestBean
{
    public TestBeanChild(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["test1C"].IsNumber) { throw new SerializationException(); }  Test1C = _buf["test1C"]; }
        { if(!_buf["test2C"].IsNumber) { throw new SerializationException(); }  Test2C = _buf["test2C"]; }
    }

    public static TestBeanChild DeserializeTestBeanChild(JSONNode _buf)
    {
        return new TestBeanChild(_buf);
    }

    public readonly int Test1C;
    public readonly int Test2C;
   
    public const int __ID__ = -530198854;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "test1:" + Test1 + ","
        + "test2:" + Test2 + ","
        + "test1C:" + Test1C + ","
        + "test2C:" + Test2C + ","
        + "}";
    }
}
}

