
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace DataTables
{
public partial struct TestBeanChild1
{
    public TestBeanChild1(JSONNode _buf) 
    {
        { if(!_buf["test1C"].IsNumber) { throw new SerializationException(); }  Test1C = _buf["test1C"]; }
        { if(!_buf["test2C"].IsNumber) { throw new SerializationException(); }  Test2C = _buf["test2C"]; }
    }

    public static TestBeanChild1 DeserializeTestBeanChild1(JSONNode _buf)
    {
        return new TestBeanChild1(_buf);
    }

    public readonly int Test1C;
    public readonly int Test2C;
   

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "test1C:" + Test1C + ","
        + "test2C:" + Test2C + ","
        + "}";
    }
}
}

