
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace DataTables
{
public partial class TTestMap
{
    private readonly System.Collections.Generic.Dictionary<int, TTest> _dataMap;
    private readonly System.Collections.Generic.List<TTest> _dataList;
    
    public TTestMap(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, TTest>(count);
        _dataList = new System.Collections.Generic.List<TTest>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TTest _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.TTest.DeserializeTTest(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, TTest> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<TTest> DataList => _dataList;

    public TTest GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TTest Get(int key) => _dataMap[key];
    public TTest this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

